# Generated by Django 4.1.3 on 2022-12-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_excel_docu_excel_keyw_excel_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel',
            name='Docu',
        ),
        migrations.RemoveField(
            model_name='excel',
            name='Keyw',
        ),
        migrations.RemoveField(
            model_name='excel',
            name='Source',
        ),
    ]
